### ISSUE TITLE
[Bug] Setting memo on executing child flow

### ISSUE THREAD

**Issue by adrianbeloqui** [temporalio/sdk-python#115]
### What are you really trying to do?

I am writing some example workflows and activities to test the capabilities of this library. As I was doing so, while trying to execute a child flow with the memo argument set I get an exception that based on my very short Google search it is due to the way the value of the memo is being set on the internal object.

### Describe the bug

Setting a value for the memo parameter on `workflow.execute_child_worflow` function throws the exception `ValueError: Direct assignment of submessage not allowed`

Here is the stacktrace:

```bash
2022-08-29 20:48:27,646 - WARNING - Failed activation on workflow EventAutomation with ID event-automation and run ID 9dca34d6-af85-4992-8abc-dd18d5a7b6da
Traceback (most recent call last):
  File "/home/vscode/.cache/pypoetry/virtualenvs/temporal-python--nLrvWXT-py3.10/lib/python3.10/site-packages/temporalio/worker/workflow_instance.py", line 266, in activate
    self._run_once()
  File "/home/vscode/.cache/pypoetry/virtualenvs/temporal-python--nLrvWXT-py3.10/lib/python3.10/site-packages/temporalio/worker/workflow_instance.py", line 1153, in _run_once
    raise self._current_activation_error
  File "/home/vscode/.cache/pypoetry/virtualenvs/temporal-python--nLrvWXT-py3.10/lib/python3.10/site-packages/temporalio/worker/workflow_instance.py", line 1170, in _run_top_level_workflow_function
    await coro
  File "/home/vscode/.cache/pypoetry/virtualenvs/temporal-python--nLrvWXT-py3.10/lib/python3.10/site-packages/temporalio/worker/workflow_instance.py", line 601, in run_workflow
    result = await self._inbound.execute_workflow(input)
  File "/home/vscode/.cache/pypoetry/virtualenvs/temporal-python--nLrvWXT-py3.10/lib/python3.10/site-packages/temporalio/worker/workflow_instance.py", line 1405, in execute_workflow
    return await input.run_fn(*args)
  File "/workspaces/saul-sample-temporal-python/temporal_python/workflows/event_automation.py", line 84, in run
    incident = await self.create_incident(params)
  File "/workspaces/saul-sample-temporal-python/temporal_python/workflows/event_automation.py", line 35, in create_incident
    incident = await workflow.execute_child_workflow(
  File "/home/vscode/.cache/pypoetry/virtualenvs/temporal-python--nLrvWXT-py3.10/lib/python3.10/site-packages/temporalio/workflow.py", line 3095, in execute_child_workflow
    handle = await _Runtime.current().workflow_start_child_workflow(
  File "/home/vscode/.cache/pypoetry/virtualenvs/temporal-python--nLrvWXT-py3.10/lib/python3.10/site-packages/temporalio/worker/workflow_instance.py", line 846, in workflow_start_child_workflow
    return await self._outbound.start_child_workflow(
  File "/home/vscode/.cache/pypoetry/virtualenvs/temporal-python--nLrvWXT-py3.10/lib/python3.10/site-packages/temporalio/worker/workflow_instance.py", line 1475, in start_child_workflow
    return await self._instance._outbound_start_child_workflow(input)
  File "/home/vscode/.cache/pypoetry/virtualenvs/temporal-python--nLrvWXT-py3.10/lib/python3.10/site-packages/temporalio/worker/workflow_instance.py", line 1052, in _outbound_start_child_workflow
    handle._apply_start_command(self._add_command())
  File "/home/vscode/.cache/pypoetry/virtualenvs/temporal-python--nLrvWXT-py3.10/lib/python3.10/site-packages/temporalio/worker/workflow_instance.py", line 1739, in _apply_start_command
    v.memo[k] = self._instance._payload_converter.to_payloads([val])[0]
ValueError: Direct assignment of submessage not allowed
```

### Minimal Reproduction

```python
await workflow.execute_child_workflow(
            "ChildWorkflow",
            {"key1": 1, "key2": 2},
            id="child-workflow-1",
            task_timeout=timedelta(seconds=120),
            memo={"my_memo_key": "my memo value"},
            retry_policy=RetryPolicy(
                backoff_coefficient=2.0,
                maximum_interval=timedelta(seconds=120),
                maximum_attempts=5,
                non_retryable_error_types=["MyCustomNonRetriableException"],
            ),
            search_attributes={"search_attribute1": [""], "search_attribute2": [""]}
)
```

### Environment/Versions

- OS and processor: Mac running Colima
- Temporal Version: `temporalio = "^0.1b1"`
- Are you using Docker or Kubernetes or building Temporal from source? Using Temporal's docker-compose provided environment. Executing workflow from a VSCode Dev Container using Python 3.10.6

### Additional context

Nothing to add at this point

**Comment by cretz** [comment]
Thanks! This is definitely a bug where I am not using the proto library properly at https://github.com/temporalio/sdk-python/blob/4db14cc7cdc01b83be656b9086ecf77aeacfac8b/temporalio/worker/workflow_instance.py#L1739 and I did not properly cover this in tests. To give background, with the Python proto SDK, you can't set messages directly on maps/lists. You have to lazily set scalar fields only via lazy message field access. I will fix this, thanks!
