### ISSUE TITLE
[Bug] Enum HistoryEventFilterType has no value defined for name 'ValueType'

### ISSUE THREAD

**Issue by grizzlybearer** [temporalio/sdk-python#288]
### What are you really trying to do?

Trying to run this example: https://github.com/temporalio/samples-python/blob/main/hello/hello_activity_multiprocess.py

### Describe the bug
Code sample crashes, but the workflow continues to run

Getting the following error:
```
Traceback (most recent call last):
  File "hello_activity_multiprocess.py", line 85, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "hello_activity_multiprocess.py", line 75, in main
    result = await client.execute_workflow(
  File "/Users/grizzlybear/.pyenvs/python3.8/lib/python3.8/site-packages/temporalio/client.py", line 556, in execute_workflow
    return await (
  File "/Users/grizzlybear/.pyenvs/python3.8/lib/python3.8/site-packages/temporalio/client.py", line 870, in result
    async for event in self._fetch_history_events_for_run(
  File "/Users/grizzlybear/.pyenvs/python3.8/lib/python3.8/site-packages/temporalio/client.py", line 1970, in __anext__
    await self.fetch_next_page()
  File "/Users/grizzlybear/.pyenvs/python3.8/lib/python3.8/site-packages/temporalio/client.py", line 1944, in fetch_next_page
    history_event_filter_type=temporalio.api.enums.v1.HistoryEventFilterType.ValueType(
  File "/Users/grizzlybear/.pyenvs/python3.8/lib/python3.8/site-packages/google/protobuf/internal/enum_type_wrapper.py", line 114, in __getattr__
    raise AttributeError('Enum {} has no value defined for name {!r}'.format(
AttributeError: Enum HistoryEventFilterType has no value defined for name 'ValueType'
```

### Minimal Reproduction

https://github.com/temporalio/samples-python/blob/main/hello/hello_activity_multiprocess.py

### Environment/Versions

- OS and processor: Mac
- Temporal Version: [e.g. 1.14.0?] and/or SDK version -> 2.10.3 (from UI)
- Are you using Docker or Kubernetes or building Temporal from source? Docker

**Comment by cretz** [comment]
Which protobuf version? This was added in 3.20+: https://github.com/protocolbuffers/protobuf/commit/0707f2e7f556c8396d6027d0533ec3a56d1061db. Make sure you are using at least the minimum version we require.

**Comment by grizzlybearer** [comment]
That was it. I upgraded to version 3.20.0 and that resolved the issue. Thanks for the quick turnaround!
I'm not sure how I was able to use temporal without it meeting this requirement.
