### ISSUE TITLE
[Bug] GeneratorExit possibly causing issues on context detach in OTel finally

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-python#441]
### Describe the bug

Reports of:

```
Failed to detach context

Traceback (most recent call last):
  File "/path/to/temporalio/contrib/opentelemetry.py", line 427, in _top_level_workflow_context
    yield None
  File "/path/to/temporalio/contrib/opentelemetry.py", line 340, in execute_workflow
    return await super().execute_workflow(input)
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/opentelemetry/context/__init__.py", line 157, in detach
    _RUNTIME_CONTEXT.detach(token)  # type: ignore
  File "/path/to/opentelemetry/context/contextvars_context.py", line 50, in detach
    self._current_context.reset(token)  # type: ignore
ValueError: <Token var=<ContextVar name='current_context' default={} at 0x79340011d590> at 0x7933a4b4c9c0> was created in a different Context"
```

There are outstanding issues like https://github.com/open-telemetry/opentelemetry-python/issues/2606 that may be related.

**Comment by jpcarlino** [comment]
Is there any workaround for this? We have tons of these errors in our logs forcing us to disable tracing in our workers.

**Comment by benliddicott** [comment]
@cretz  As I commented on #2606 I was able to work around a similar issue. Feel free to contact me if you are interested in more details.
https://github.com/open-telemetry/opentelemetry-python/issues/2606#issuecomment-1789515786

**Comment by matthewgrossman** [comment]
Hey @benliddicott I've been following this issue for OTEL for awhile, and put out a flask-specific fix awhile back: https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1692. Since you're still recently having issues, I'm imagining that didn't resolve it for you (unless you're on an old version?)

Maybe the changes / PR desc could be helpful debugging your issue?

**Comment by cretz** [comment]
For the Temporal SDK here in this GH issue, we don't even use Flask. The GC can wake up the coroutine in any thread, including the same one it may have started in but is currently being used for something else by the thread pool. There's not much you can do but avoid letting coroutines/generators get GC'd.

**Comment by matthewgrossman** [comment]
Ya sorry about the flask noise, probably better to post what I did back in https://github.com/open-telemetry/opentelemetry-python/issues/2606

I'm now on a new project where we're running into the same error, and it's moreso related to generators/coroutines that you are mentioning, so that's why I'm also following this thread

**Comment by cretz** [comment]
No prob, yeah I flat out could not find a good solution besides not ever reaching `GeneratorExit` (or coroutine GC). There's no way to disable this behavior, no way to intercept, and with threading (especially thread pools) no guarantee where it may wake up.

**Comment by benliddicott** [comment]
@matthewgrossman I am not having issues, as I have a workaround, as described in https://github.com/open-telemetry/opentelemetry-python/issues/2606#issuecomment-1789515786 so there is no urgency from my side.

**Comment by hellais** [comment]
@benliddicott would you be available to share the code you used as a solution to this? I am running into the same issue as well.
