### ISSUE TITLE
Cannot execute workflow update from a temporal activity

### ISSUE THREAD

**Issue by sytdas** [temporalio/sdk-python#633]
I have 2 workflows, one run by schedule to fetch updates and send it to a long running workflow which hold some state. When I tried to send update using activity, I got following error.

```
Error: ({'activity_id': '2', 'activity_type': 'update_workflow', 'attempt': 1, 'namespace': 'default', 'task_queue': 'hello-cron-task-queue-schedule', 'workflow_id': 'hello-cron-workflow-id-scheduler', 'workflow_run_id': 'b3495343-a347-4706-8b62-0be845b46ded', 'workflow_type': 'GreetingCronWorkflow'})
Traceback (most recent call last):
  File "/Users/sytd/Code/sytd/temporal-update/.venv/lib/python3.12/site-packages/temporalio/service.py", line 1064, in _rpc_call
    resp = await client.call(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sytd/Code/sytd/temporal-update/.venv/lib/python3.12/site-packages/temporalio/bridge/client.py", line 151, in call
    resp.ParseFromString(await resp_fut)
                         ^^^^^^^^^^^^^^
temporal_sdk_bridge.RPCError: (9, 'limit on number of total updates has been reached (2000)', b'')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sytd/Code/sytd/temporal-update/main.py", line 98, in update_workflow
    return await handler.execute_update(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sytd/Code/sytd/temporal-update/.venv/lib/python3.12/site-packages/temporalio/client.py", line 1862, in execute_update
    handle = await self._start_update(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sytd/Code/sytd/temporal-update/.venv/lib/python3.12/site-packages/temporalio/client.py", line 2013, in _start_update
    return await self._client._impl.start_workflow_update(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sytd/Code/sytd/temporal-update/.venv/lib/python3.12/site-packages/temporalio/client.py", line 5294, in start_workflow_update
    resp = await self._client.workflow_service.update_workflow_execution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sytd/Code/sytd/temporal-update/.venv/lib/python3.12/site-packages/temporalio/service.py", line 991, in __call__
    return await self.service_client._rpc_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sytd/Code/sytd/temporal-update/.venv/lib/python3.12/site-packages/temporalio/service.py", line 1079, in _rpc_call
    raise RPCError(message, RPCStatusCode(status), details)
temporalio.service.RPCError: limit on number of total updates has been reached (2000)
```
Here is the code https://github.com/sytdas/temporal-update

**Comment by sytdas** [comment]
I can trigger the update from temporal cli. Now I need to make it work with the scheduled workflow activity.

**Comment by sytdas** [comment]
There's a bug in my code when sending invalid data.
